# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kx9ihPc_zWThjkX8pVdU6erPUGOReGkb
"""

import pandas as pd
url = "https://raw.githubusercontent.com/Devinda-27/supermarket_sales/6d2f7be684e43ec8cad547e4ccf94130dc67cbc8/supermarket_Sales.csv"
df = pd.read_csv(url)
df.head()

# Ambil fitur numerik saja
X = df[['Gross income', 'Customer stratification rating']]
X.head()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Model KMeans
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(X)

# Hasil
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

# Plot
plt.scatter(X.iloc[:,0], X.iloc[:,1], c=labels, cmap='viridis')
plt.scatter(centroids[:,0], centroids[:,1], s=200, c='red')
plt.xlabel('Gross income')
plt.ylabel('Customer stratification rating')
plt.title('K-Means Clustering')
plt.show()

inertia = []
K = range(1,10)

for k in K:
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.plot(K, inertia, marker='o')
plt.xlabel('Jumlah Cluster (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Model KMeans
kmeans = KMeans(n_clusters=5, random_state=0)
kmeans.fit(X)

# Hasil
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

# Plot
plt.scatter(X.iloc[:,0], X.iloc[:,1], c=labels, cmap='viridis')
plt.scatter(centroids[:,0], centroids[:,1], s=200, c='red')
plt.xlabel('Gross income')
plt.ylabel('Customer stratification rating')
plt.title('K-Means Clustering')
plt.show()

import pickle

# simpan model
with open('model.pkl', 'wb') as file:
    pickle.dump(kmeans, file)
